- Pandas <br>
- Loading the Data<br>
- Dataframe

In [ ]:
# Install Pandas
!pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [ ]:
# Import Library
import pandas as pd

In [ ]:
# Data Frame
# Loading the Data
df = pd.read_csv("/content/sample_data/vgsalesGlobale.csv", index_col ="Name")

In [ ]:
df.head()

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Wii Sports,1,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
Super Mario Bros.,2,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
Mario Kart Wii,3,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
Wii Sports Resort,4,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
Pokemon Red/Pokemon Blue,5,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [ ]:
df.tail(10)

,Rank,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Name,,,,,,,,,,
Mega Brain Boost,16591,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.0,0.01
Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shirube Kareru,16592,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.0,0.01
Eiyuu Densetsu: Sora no Kiseki Material Collection Portable,16593,PSP,2007.0,Role-Playing,Falcom Corporation,0.00,0.00,0.01,0.0,0.01
Myst IV: Revelation,16594,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.0,0.01
Plushees,16595,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.0,0.01
Woody Woodpecker in Crazy Castle 5,16596,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.0,0.01
Men in Black II: Alien Escape,16597,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.0,0.01
SCORE International Baja 1000: The Official Game,16598,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.0,0.01
Know How 2,16599,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.0,0.01
Spirits & Spells,16600,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.0,0.01

In [ ]:
df.shape

(16598, 10)

In [ ]:
df.dtypes

Rank              int64
Platform         object
Year            float64
Genre            object
Publisher        object
NA_Sales        float64
EU_Sales        float64
JP_Sales        float64
Other_Sales     float64
Global_Sales    float64
dtype: object

**Data Types**

Data types bohat zaroori hain kyun k ye computer ko batate hain ke data ko kis tarah se samjhein aur us par kya amal karein. Data types har programming language mein mojood hote hain aur har qisam ke data ko sahi tareeqe se store aur process karne ke liye zaroori hain.

Data types ki madad se hum ye bhi yakeen kar sakte hain ke jo data hum collect kar rahe hain wo sahi format aur value mein hai. Jaise agar hum kisi ka naam store karna chahte hain to hum us ko string data type mein rakhenge, aur agar hum kisi ka phone number store karna chahte hain to hum us ko integer data type mein rakhenge.

Data types ke bohat se qisam hain, jaise integer, float, string, boolean, date, time, array, etc. Har data type ka apna maqsad aur istemal hai. Jaise integer data type sirf mukammal numbers ko store karta hai, float data type decimal numbers ko store karta hai, string data type text ya characters ko store karta hai, boolean data type sirf true ya false values ko store karta hai, date data type tareekh ko store karta hai, time data type waqt ko store karta hai, array data type aik list ya silsila ko store karta hai, etc

## --int64 <br>
## --object <br>
##--float64

-- **int64**: int64 aik qisam ka data hai jo sirf mukammal numbers ko store kar sakta hai. Mukammal numbers wo hain jo koi decimal point ya fraction na hon, jaise 1, 2, 3, … Int64 ka matlab hai ke is data type mein aik number ko store karne ke liye 64 bits ki zaroorat hoti hai. Aik bit aik chota sa switch hai jo sirf do states mein ho sakta hai: on ya off, ya 1 ya 0. Int64 mein hum 2^64 mukhtalif numbers ko store kar sakte hain.

-- **object**: object aik qisam ka data hai jo kisi bhi cheez ko store kar sakta hai. Object mein hum text, numbers, dates, ya koi bhi aur data rakh sakte hain. Object flexible hai lekin is ki efficiency kam hoti hai. Object ko hum container keh sakte hain jo kuch bhi rakh sakta hai.

-- **float64**: float64 aik qisam ka data hai jo decimal point ya fraction wale numbers ko store kar sakta hai. Jaise 1.5, 3.14, 0.25, … Float64 ka matlab hai ke is data type mein aik number ko store karne ke liye 64 bits ki zaroorat hoti hai. Float64 mein hum bohat saare decimal numbers ko store kar sakte hain lekin un ki accuracy poori nahi hoti.